### PR TITLE
Tested, this is the complete Mapping extensions Mod

### PR DESCRIPTION
**Pull request by caffeine239**

### CODE REVIEW

**Comment by isenmann** [comment]
Testing the pull request right now locally, need some time to check it. Thanks in advance for this...will give feedback asap

**Comment by caffeine239** [comment]
i would suggest looking into a different way of moving blocks to beat, also use some object pooling :) Heres a small video of mapping extensions for notes. https://www.youtube.com/watch?v=8ZMYYSOENWg&feature=youtu.be

**Comment by isenmann** [comment]
> i would suggest looking into a different way of moving blocks to beat

As I wrote it in the header of the NoteSpawner.cs file, the spawning part was more or less ported from the BeatSaver viewer project and I was happy that I have somehting working ;-)

>also use some object pooling :) Heres a small video of mapping extensions for notes. 
https://www.youtube.com/watch?v=8ZMYYSOENWg&feature=youtu.be

WTF!!!  It's like a psychedelic trip :-D But yeah, object pooling would be better if a map has this lots of notes. Happy about any improvement ;-)

**Comment by caffeine239** [comment]
> > i would suggest looking into a different way of moving blocks to beat
> 
> As I wrote it in the header of the NoteSpawner.cs file, the spawning part was more or less ported from the BeatSaver viewer project and I was happy that I have somehting working ;-)
> 
> > also use some object pooling :) Heres a small video of mapping extensions for notes.
> > https://www.youtube.com/watch?v=8ZMYYSOENWg&feature=youtu.be
> 
> WTF!!! It's like a psychedelic trip :-D But yeah, object pooling would be better if a map has this lots of notes. Happy about any improvement ;-)

Object pooling is just better on unity, also you could use 1 note prefab instead of 4. Im doing the walls now. im not sure how the game was before but do the notes move correctly like before?

**Comment by isenmann** [comment]
> Object pooling is just better on unity

I know, but never used before ;-)

> you could use 1 note prefab instead of 4.

I know, but starting with 4 was the fastest in the beginning. 

> Im doing the walls now.

You're really crazy.... :-D

> im not sure how the game was before but do the notes move correctly like before?

The notes move correctly and are in time. The distance between the far left and the far right is just a little bit large. I can barly hit them if they appear simultaniously at the player and I'm not a small person ;-)

**Comment by caffeine239** [comment]
In my change, the distance is a bit large from left to right?

**Comment by isenmann** [comment]
> In my change, the distance is a bit large from left to right?

Yes, could be a little bit smaller.

**Comment by caffeine239** [comment]
These numbers are exactly as beatsaber uses, also this is a must do change hit boxes on notes to like this. 
image

**Comment by isenmann** [comment]
Okay, then it's fine. But then I think I have to increase the size of the notes a little bit. Another user told me already, that they are a little bit small

**Comment by isenmann** [comment]
Tested with some larger blocks and now it's fine, so it was really the size of the notes. So the positions are fine

**Comment by caffeine239** [comment]
yes size of block is key. dont forget to change that box collider tho. it does wonders and this is also how beat saber does it :)

**Pull request merged**
