### PR TITLE
Support for all game types (one/two sabers and so on) #7

### PR DESCRIPTION
**Pull request by dhcdht**
Support for all available game types in the _beatmapCharacteristicName array.

### CODE REVIEW

**Comment by isenmann** [comment]
I'm on holidays right now and will be back on August 12th. I will have a look as soon as I have a computer available again. So expect the earliest action on this in about 11 days.

**Comment by isenmann** [comment]
I have merged the highscore branch, could you resolve the conflicting files in this pull request? Thanks....

**Comment by dhcdht** [comment]
> I have merged the highscore branch into develop, could you resolve the conflicting files in this pull request? Thanks....

Resolved

**Comment by isenmann** [comment]
Thanks, looks good. I will merge it after the release.

**Comment by isenmann** [comment]
Merged your changes into a new branch which is called feature/GameTypes. It was branched from the latest develop branch, so it's uptodate with the latest code base.
If you do new stuff then just branch it from the new feature/GameTypes branch and do a pull request against it. 
Thanks for the work!

**Pull request closed without merging**
